id = "dwp-theme"
name = "Dwp theme"
version = "0.0.1"
schema_version = 1
authors = ["Sachin Jangir <sachinjangir0181@gmail.com>"]
description = "A theme for perfectionists"
repository = "https://github.com/shenlong21/zed-dwp-theme"
